name: Build

on:
  push:
    branches:
      - "main"
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
  pull_request:
    branches:
      - "main"

jobs:
  build:
    name: Build & Publish
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v3.2.1

      - name: Determine Version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v3.2.1
        with:
          useConfigFile: true
          configFilePath: GitVersion.yml

      - name: Install NPM Packages
        shell: pwsh
        run: npm i

      - name: Build Project
        shell: pwsh
        run: npm run build

      - name: Run NPM verision
        shell: pwsh
        run: |
          npm version ${{ steps.gitversion.outputs.fullSemVer }} --no-git-tag-version

      - name: Publish to NPM
        shell: pwsh
        run: |
          Write-Host "$NODE_AUTH_TOKEN".Length

          if ("${{ github.ref_type }}" -eq "tag") {
            npm publish --access public
          } else {
            npm publish --tag prerelease --access public
          }
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}